### PR TITLE
Kubernetes v1.3.9

### PR DESCRIPTION
**Pull request by bcwaldon**

### CODE REVIEW

**Comment by bcwaldon** [comment]
Everything seems to be fine w/ k8s v1.3.9 without any config changes. @jk0 is this ok with you?

**Comment by jk0** [comment]
+1 As long as we're not running into that network bridge issue (1.3.8 and 1.4.0 I believe).

**Comment by bcwaldon** [comment]
@jk0 I was able to bring up a cluster successfully and deploy a full application atop it, which I assume would not work if there were an issue with the bridge management. Does that sound right?

**Comment by bcwaldon** [comment]
I just vendored in a modified version of the guestbook-go example [0] that works on top of k8s v1.3.9. I'm going to move forward here.

[0] https://github.com/bcwaldon/klondike/blob/master/contrib/example-guestbook.yml

**Comment by jk0** [comment]
Yeah, you would not have been able to deploy the cluster services if the issue was still present.

**Pull request merged**
