### PR TITLE
List DNS records in cluster-info.

### PR DESCRIPTION
**Pull request by jacobstr**

### CODE REVIEW

**Comment by posix4e** [comment]
Any reason why we don't merge this?

**Comment by bcwaldon** [comment]
@jacobstr sample output?

**Comment by jacobstr** [comment]
```
stack_name: klondike-cluster-charmeleon
stack_status: CREATE_COMPLETE
stack_dns: ['logs.charmeleon.prod.k8s.planet-labs.com', 'bastion.charmeleon.prod.k8s.planet-labs.com', 'api.charmeleon.prod.k8s.planet-labs.com', '*.gateway.charmeleon.prod.k8s.planet-labs.com']
bastion_host: bastion.charmeleon.prod.k8s.planet-labs.com
worker_asg_capacity: 1
worker_count: 1
worker_asg_name: klondike-cluster-charmeleon-WorkerASG-13ZLOI40TAHCG
```

**Comment by bcwaldon** [comment]
@jacobstr I'm not really convinced this is useful. The bastion_host field is contained inside of stack_dns, for example. What was the use case you were trying to solve?

**Comment by bcwaldon** [comment]
This is getting less useful as time goes on, and `logs` is on its way out. Re-open if you feel strongly.

**Pull request closed without merging**
